require:
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 2.5.1
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  DisabledByDefault: true
  Exclude:
    - 'db/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'lib/active_storage/service/compat_s3_service.rb'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'
    - 'config/**/*.rb'

Community/FactoryGirlPrefix:
  Enabled: true
  Include:
    - 'spec/**/*_spec.rb'

Community/CommunityServiceCheck:
  Enabled: true

Community/RSpecRequireCheck:
  Enabled: true
  Include:
    - 'spec/**/*_spec.rb'

Performance/OpenStruct:
  Enabled: true

Performance/Caller:
  Enabled: true

Performance/CaseWhenSplat:
  Enabled: true

Performance/Casecmp:
  Enabled: true

ThreadSafety:
  Enabled: true

# to be reenabled once codeclimate releases 0.59 channel
Performance/ChainArrayAllocation:
  Enabled: true

Performance/CompareWithBlock:
  Enabled: true

Performance/Count:
  Enabled: true

Performance/Detect:
  Enabled: true

Performance/DoubleStartEndWith:
  Enabled: true

Performance/EndWith:
  Enabled: true

Performance/FixedSize:
  Enabled: true

Performance/FlatMap:
  Enabled: true

Performance/InefficientHashSearch:
  Enabled: true

Style/Strip:
  Enabled: true

Performance/RangeInclude:
  Enabled: true

Performance/RedundantBlockCall:
  Enabled: true

Performance/RedundantMatch:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Style/RedundantSortBy:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

Performance/ReverseEach:
  Enabled: true

Style/Sample:
  Enabled: true

Performance/Size:
  Enabled: true

Performance/StartWith:
  Enabled: true

Performance/StringReplacement:
  Enabled: true

Performance/TimesMap:
  Enabled: true

Performance/UnfreezeString:
  Enabled: true

Style/UnneededSort:
  Enabled: true

Performance/UriDefaultParser:
  Enabled: true

Naming/AccessorMethodName:
  Enabled: true

Naming/AsciiIdentifiers:
  Enabled: true

Naming/BinaryOperatorParameterName:
  Enabled: true

Naming/ClassAndModuleCamelCase:
  Enabled: true

Naming/ConstantName:
  Enabled: true

Naming/FileName:
  Enabled: true

Naming/HeredocDelimiterCase:
  Enabled: true

Naming/HeredocDelimiterNaming:
  Enabled: true

Naming/MemoizedInstanceVariableName:
  Enabled: true

Naming/MethodName:
  Enabled: true

Naming/PredicateName:
  Enabled: true

Naming/UncommunicativeBlockParamName:
  Enabled: true

Naming/UncommunicativeMethodParamName:
  Enabled: true

Naming/VariableName:
  Enabled: true

Naming/VariableNumber:
  Enabled: true

Lint/DisjunctiveAssignmentInConstructor:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: true

Lint/AmbiguousRegexpLiteral:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: true

Lint/BigDecimalNew:
  Enabled: true

Lint/BooleanSymbol:
  Enabled: true

Lint/CircularArgumentReference:
  Enabled: true

Lint/Debugger:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/DuplicateCaseCondition:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/DuplicatedKey:
  Enabled: true

Lint/EachWithObjectArgument:
  Enabled: true

Lint/ElseLayout:
  Enabled: true

Lint/EmptyEnsure:
  Enabled: true

Lint/EmptyExpression:
  Enabled: true

Lint/EmptyInterpolation:
  Enabled: true

Lint/EmptyWhen:
  Enabled: true

Lint/EndInMethod:
  Enabled: true

Lint/EnsureReturn:
  Enabled: true

Lint/FloatOutOfRange:
  Enabled: true

Lint/FormatParameterMismatch:
  Enabled: true

Lint/HandleExceptions:
  Enabled: true

Lint/ImplicitStringConcatenation:
  Enabled: true

Lint/IneffectiveAccessModifier:
  Enabled: true

Lint/InheritException:
  Enabled: true

Lint/InterpolationCheck:
  Enabled: true

Lint/LiteralAsCondition:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Lint/Loop:
  Enabled: true

Lint/MissingCopEnableDirective:
  Enabled: true

Lint/MultipleCompare:
  Enabled: true

Lint/NestedMethodDefinition:
  Enabled: true

Lint/NestedPercentLiteral:
  Enabled: true

Lint/NextWithoutAccumulator:
  Enabled: true

Lint/NonLocalExitFromIterator:
  Enabled: true

Lint/NumberConversion:
  Enabled: true

Lint/OrderedMagicComments:
  Enabled: true

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Lint/PercentStringArray:
  Enabled: true

Lint/PercentSymbolArray:
  Enabled: true

Lint/RandOne:
  Enabled: true

Lint/RedundantWithIndex:
  Enabled: true

Lint/RedundantWithObject:
  Enabled: true

Lint/RegexpAsCondition:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Lint/RescueException:
  Enabled: true

Lint/RescueType:
  Enabled: true

Lint/ReturnInVoidContext:
  Enabled: true

Lint/SafeNavigationChain:
  Enabled: true

Lint/SafeNavigationConsistency:
  Enabled: true

Lint/ScriptPermission:
  Enabled: true

Lint/ShadowedArgument:
  Enabled: true

Lint/ShadowedException:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/StringConversionInInterpolation:
  Enabled: true

Lint/UnderscorePrefixedVariableName:
  Enabled: true

Lint/UnifiedInteger:
  Enabled: true

Lint/UnneededCopDisableDirective:
  Enabled: true

Lint/UnneededCopEnableDirective:
  Enabled: true

Lint/UnneededRequireStatement:
  Enabled: true

Lint/UnneededSplatExpansion:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Lint/UriEscapeUnescape:
  Enabled: true

Lint/UriRegexp:
  Enabled: true

Lint/UselessAccessModifier:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Lint/UselessComparison:
  Enabled: true

Lint/UselessElseWithoutRescue:
  Enabled: true

Lint/UselessSetterCall:
  Enabled: true

Lint/Void:
  Enabled: true

Metrics/ParameterLists:
  Enabled: true

Metrics/PerceivedComplexity:
  Enabled: true

Rails/ActionFilter:
  Enabled: true

Rails/ActiveRecordAliases:
  Enabled: true

Rails/ActiveSupportAliases:
  Enabled: true

Rails/ApplicationJob:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: true

Rails/Blank:
  Enabled: true

Rails/BulkChangeTable:
  Enabled: true

Rails/CreateTableWithTimestamps:
  Enabled: true

Rails/Date:
  Enabled: true

Rails/Delegate:
  Enabled: true

Rails/DelegateAllowBlank:
  Enabled: true

Rails/DynamicFindBy:
  Enabled: true

Rails/EnumUniqueness:
  Enabled: true

Rails/EnvironmentComparison:
  Enabled: true

Rails/Exit:
  Enabled: true

Rails/FilePath:
  Enabled: true

Rails/FindBy:
  Enabled: true

Rails/FindEach:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: true

Rails/HttpStatus:
  Enabled: true

Rails/InverseOf:
  Enabled: true

Rails/LexicallyScopedActionFilter:
  Enabled: true

Rails/NotNullColumn:
  Enabled: true

Rails/Output:
  Enabled: true

Rails/OutputSafety:
  Enabled: true

Rails/Presence:
  Enabled: true

Rails/Present:
  Enabled: true

Rails/ReadWriteAttribute:
  Enabled: true

Rails/RedundantReceiverInWithOptions:
  Enabled: true

Rails/RelativeDateConstant:
  Enabled: true

Rails/RequestReferer:
  Enabled: true

Rails/ReversibleMigration:
  Enabled: true

Rails/SafeNavigation:
  Enabled: true

Rails/SaveBang:
  Enabled: true

Rails/ScopeArgs:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: true

Rails/TimeZone:
  Enabled: true

Rails/UniqBeforePluck:
  Enabled: true

Rails/UnknownEnv:
  Enabled: true

Rails/Validation:
  Enabled: true

Security/Eval:
  Enabled: true

Security/JSONLoad:
  Enabled: true

Security/MarshalLoad:
  Enabled: true

Security/Open:
  Enabled: true

Security/YAMLLoad:
  Enabled: true

Style/AccessModifierDeclarations:
  Enabled: true

Style/Alias:
  Enabled: true

Style/AndOr:
  Enabled: true

Style/ArrayJoin:
  Enabled: true

Style/Attr:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/BarePercentLiterals:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true

Style/BracesAroundHashParameters:
  Enabled: true

Style/CaseEquality:
  Enabled: true

Style/CharacterLiteral:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: true

Style/ClassCheck:
  Enabled: true

Style/ClassMethods:
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/ColonMethodCall:
  Enabled: true

Style/ColonMethodDefinition:
  Enabled: true

Style/CommandLiteral:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: true

Style/DateTime:
  Enabled: false

Style/DefWithParentheses:
  Enabled: true

Style/Dir:
  Enabled: true

Style/DoubleNegation:
  Enabled: true

Style/EachForSimpleLoop:
  Enabled: true

Style/EachWithObject:
  Enabled: true

Style/EmptyBlockParameter:
  Enabled: true

Style/EmptyCaseCondition:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Style/EmptyLambdaParameter:
  Enabled: true

Style/EmptyLiteral:
  Enabled: true

Style/EmptyMethod:
  Enabled: true

Style/EvalWithLocation:
  Enabled: true

Style/EvenOdd:
  Enabled: true

Style/ExpandPathArguments:
  Enabled: true

Style/For:
  Enabled: true

Style/FormatString:
  Enabled: true

Style/GlobalVars:
  Enabled: true
  AllowedVariables: ["$log"]

Style/HashSyntax:
  Enabled: true

Style/IdenticalConditionalBranches:
  Enabled: true

Style/IfInsideElse:
  Enabled: true

# to be reenabled once codeclimate releases 0.59 channel
# Style/IfUnlessModifier:
#   Enabled: true

Style/IfUnlessModifierOfIfUnless:
  Enabled: true

Style/IfWithSemicolon:
  Enabled: true

Style/ImplicitRuntimeError:
  Enabled: true

Style/InfiniteLoop:
  Enabled: true

Style/InlineComment:
  Enabled: true

Style/InverseMethods:
  Enabled: true

Style/Lambda:
  Enabled: true

Style/LambdaCall:
  Enabled: true

Style/LineEndConcatenation:
  Enabled: true

Style/MethodCallWithoutArgsParentheses:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/MethodMissingSuper:
  Enabled: true

Style/MinMax:
  Enabled: true

Style/MissingRespondToMissing:
  Enabled: true

Style/MixinGrouping:
  Enabled: true

Style/MixinUsage:
  Enabled: true

Style/ModuleFunction:
  Enabled: true

Style/MultilineMemoization:
  Enabled: true

Style/MultipleComparison:
  Enabled: true

Style/MutableConstant:
  Enabled: true

Style/NegatedWhile:
  Enabled: true

Style/NestedParenthesizedCalls:
  Enabled: true

Style/NestedTernaryOperator:
  Enabled: true

Style/Next:
  Enabled: true

Style/NumericLiterals:
  Enabled: true

Style/NumericPredicate:
  Enabled: true

Style/OptionalArguments:
  Enabled: true

Style/OrAssignment:
  Enabled: true

Style/ParenthesesAroundCondition:
  Enabled: true

Style/PreferredHashMethods:
  Enabled: true

Style/Proc:
  Enabled: true

Style/RaiseArgs:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/RedundantException:
  Enabled: true

Style/RedundantFreeze:
  Enabled: true

Style/RedundantParentheses:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/RegexpLiteral:
  Enabled: true

Style/RescueModifier:
  Enabled: true

Style/ReturnNil:
  Enabled: true

Style/SafeNavigation:
  Enabled: true

Style/SelfAssignment:
  Enabled: true

Style/Send:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Style/StabbyLambdaParentheses:
  Enabled: true

Style/StringHashKeys:
  Enabled: true
  Exclude:
    - 'config/environments/*.rb'
    - 'spec/**/*'

Style/StructInheritance:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/SymbolLiteral:
  Enabled: true

Style/SymbolProc:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  Enabled: true

Style/UnneededCondition:
  Enabled: true

Style/UnneededInterpolation:
  Enabled: true

# Prefer x.nil? to x == nil.
Style/NilComparison:
  Enabled: true

# Checks the indentation of hanging closing parentheses.
Layout/ClosingParenthesisIndentation:
  Enabled: true

# Only use if/unless modifiers on single line statements.
Style/MultilineIfModifier:
  StyleGuide: '#no-multiline-if-modifiers'
  Enabled: true

# Use ! instead of not.
Style/Not:
  Enabled: true

# Use 2 spaces for indentation.
Layout/IndentationWidth:
  Enabled: true

# Use 2 spaces for indentation in an array, relative to the first position after the preceding left parenthesis.
Layout/IndentFirstArrayElement:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

# Line is too long. [120]
Metrics/LineLength:
  Enabled: true
  Max: 120

# Checks indentation of method calls with the dot operator
# that span more than one line.
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented_relative_to_receiver

# Use `{ a: 1 }` not `{a:1}`.
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

# Don't use several empty lines in a row
Layout/EmptyLines:
  Enabled: true
# Use empty lines between defs.
Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

# Checks trailing blank lines and final newline.
Layout/TrailingBlankLines:
  Enabled: true

Layout/AlignHash:
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/AlignArray:
  Enabled: true

Layout/AlignParameters:
  Enabled: true

Layout/IndentFirstHashElement:
  Enabled: true

Layout/IndentationConsistency:
  Description: 'Keep indentation straight.'
  StyleGuide: '#spaces-indentation'
  Enabled: true
  # to be reenabled once codeclimate releases support for 0.59
#   EnforcedStyle: rails

# Check for conditionals that can be replaced with guard clauses
Style/GuardClause:
  Enabled: true
  Exclude:
    - 'app/models/draft_document.rb'

# Don't use semicolons to terminate expressions.
Style/Semicolon:
  Enabled: true

# Checks for incorrect grammar when using methods like `3.day.ago`
Rails/PluralizationGrammar:
  Enabled: true

# Checks that the closing brace in a method call is
# either on the same line as the last method argument, or
# a new line.
Layout/MultilineMethodCallBraceLayout:
  Enabled: true

# Checks that the closing brace in an array literal is
# either on the same line as the last array element, or
# a new line.
Layout/MultilineArrayBraceLayout:
  Enabled: true


Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

# Don't return true/false from a conditional
Style/RedundantConditional:
  Enabled: true


Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
